### ISSUE TITLE
Error happen at the end of processing

### ISSUE THREAD

**Issue by hlia981** [YaoFANGUK/video-subtitle-remover#113]
Hi, I had encountered an error at the end of processing. The GUI worked as normal and the preview window showed the processed image correctly. However, at the end of processing(I suspect it's tryna merge the video), it throws an error.

> system: windows11
> Total video frames: 7953

```
Traceback (most recent call last):
  File "D:\google_downloads\remover\vsr\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\google_downloads\remover\vsr\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\google_downloads\remover\vsr\resources\gui.py", line 277, in task
    self.sr.run()
  File "D:\google_downloads\remover\vsr\resources\backend\main.py", line 719, in run
    self.sttn_mode(tbar)
  File "D:\google_downloads\remover\vsr\resources\backend\main.py", line 596, in sttn_mode
    self.sttn_mode_with_no_detection(tbar)
  File "D:\google_downloads\remover\vsr\resources\backend\main.py", line 588, in sttn_mode_with_no_detection
    sttn_video_inpaint(input_mask=mask, input_sub_remover=self, tbar=tbar)
  File "D:\google_downloads\remover\vsr\resources\backend\inpaint\sttn_inpaint.py", line 273, in __call__
    image_crop = image[inpaint_area[k][0]:inpaint_area[k][1], :, :]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by HongyuMu** [comment]
Hey I'm not an expert in this but during my project I had similar errors. I would suggest checking your mask shape and ensuring that it has the 3-color channel (BGR) instead of having only 2 dimensions. Hope that helps!
