### ISSUE TITLE
输入图片没有subtitle时：IndexError: list index out of range

### ISSUE THREAD

**Issue by jiaaozhe** [YaoFANGUK/video-subtitle-remover#18]
Traceback (most recent call last):
  File "./video-subtitle-remover/backend/main.py", line 795, in <module>
    sd.run()
  File "./video-subtitle-remover/backend/main.py", line 702, in run
    sub_list = self.sub_detector.find_subtitle_frame_no(sub_remover=self)
  File "./video-subtitle-remover/backend/main.py", line 103, in find_subtitle_frame_no
    subtitle_frame_no_box_dict = self.unify_regions(subtitle_frame_no_box_dict)
  File "./video-subtitle-remover/backend/main.py", line 175, in unify_regions
    last_key = keys[0]
IndexError: list index out of range
如果输入是图片而且图片中没有subtitle时会出现如上错误

**Comment by YaoFANGUK** [comment]
好的 我修复下
