### ISSUE TITLE
視頻導出失敗 ???? WHY

### ISSUE THREAD

**Issue by Prepanpan** [YaoFANGUK/video-subtitle-remover#32]
Open Video Success：C:/Downloads/________.mp4
SubtitleArea：(20,113,1596,1896)
use GPU for acceleration
use sttn mode with no detection
[Processing] start removing subtitles...
Processing: 1 - 30  / Total: 6423
Processing: 31 - 60  / Total: 6423
Processing: 61 - 90  / Total: 6423
Processing: 91 - 120  / Total: 6423
Processing: 121 - 150  / Total: 6423
Processing: 151 - 180  / Total: 6423
Processing: 181 - 210  / Total: 6423
Processing: 211 - 240  / Total: 6423
Processing: 241 - 270  / Total: 6423
Processing: 271 - 300  / Total: 6423
Processing: 301 - 330  / Total: 6423
Processing: 331 - 360  / Total: 6423
Processing: 361 - 390  / Total: 6423
Processing: 391 - 420  / Total: 6423
Processing: 421 - 450  / Total: 6423
Processing: 451 - 480  / Total: 6423
Processing: 481 - 510  / Total: 6423
Processing: 511 - 540  / Total: 6423
Processing: 541 - 570  / Total: 6423
Processing: 571 - 600  / Total: 6423
Processing: 601 - 630  / Total: 6423
Processing: 631 - 660  / Total: 6423
Processing: 661 - 690  / Total: 6423
Processing: 691 - 720  / Total: 6423
Processing: 721 - 750  / Total: 6423
Processing: 751 - 780  / Total: 6423
Processing: 781 - 810  / Total: 6423
Processing: 811 - 840  / Total: 6423
Processing: 841 - 870  / Total: 6423
Processing: 871 - 900  / Total: 6423
Processing: 901 - 930  / Total: 6423
Processing: 931 - 960  / Total: 6423
Processing: 961 - 990  / Total: 6423
Processing: 991 - 1020  / Total: 6423
Processing: 1021 - 1050  / Total: 6423
Processing: 1051 - 1080  / Total: 6423
Processing: 1081 - 1110  / Total: 6423
Processing: 1111 - 1140  / Total: 6423
Processing: 1141 - 1170  / Total: 6423
Processing: 1171 - 1200  / Total: 6423
Processing: 1201 - 1230  / Total: 6423
Processing: 1231 - 1260  / Total: 6423
Processing: 1261 - 1290  / Total: 6423
Processing: 1291 - 1320  / Total: 6423
Processing: 1321 - 1350  / Total: 6423
Processing: 1351 - 1380  / Total: 6423
Processing: 1381 - 1410  / Total: 6423
Processing: 1411 - 1440  / Total: 6423
Processing: 1441 - 1470  / Total: 6423
Processing: 1471 - 1500  / Total: 6423
Processing: 1501 - 1530  / Total: 6423
Processing: 1531 - 1560  / Total: 6423
Processing: 1561 - 1590  / Total: 6423
Processing: 1591 - 1620  / Total: 6423
Processing: 1621 - 1650  / Total: 6423
Processing: 1651 - 1680  / Total: 6423
Processing: 1681 - 1710  / Total: 6423
Processing: 1711 - 1740  / Total: 6423
Processing: 1741 - 1770  / Total: 6423
Processing: 1771 - 1800  / Total: 6423
Processing: 1801 - 1830  / Total: 6423
Processing: 1831 - 1860  / Total: 6423
Processing: 1861 - 1890  / Total: 6423
Processing: 1891 - 1920  / Total: 6423
Processing: 1921 - 1950  / Total: 6423
Processing: 1951 - 1980  / Total: 6423
Processing: 1981 - 2010  / Total: 6423
Processing: 2011 - 2040  / Total: 6423
Processing: 2041 - 2070  / Total: 6423
Processing: 2071 - 2100  / Total: 6423
Processing: 2101 - 2130  / Total: 6423
Processing: 2131 - 2160  / Total: 6423
Processing: 2161 - 2190  / Total: 6423
Processing: 2191 - 2220  / Total: 6423
Processing: 2221 - 2250  / Total: 6423
Processing: 2251 - 2280  / Total: 6423
Processing: 2281 - 2310  / Total: 6423
Processing: 2311 - 2340  / Total: 6423
Processing: 2341 - 2370  / Total: 6423
Processing: 2371 - 2400  / Total: 6423
Processing: 2401 - 2430  / Total: 6423
Processing: 2431 - 2460  / Total: 6423
Processing: 2461 - 2490  / Total: 6423
Processing: 2491 - 2520  / Total: 6423
Processing: 2521 - 2550  / Total: 6423
Processing: 2551 - 2580  / Total: 6423
Processing: 2581 - 2610  / Total: 6423
Processing: 2611 - 2640  / Total: 6423
Processing: 2641 - 2670  / Total: 6423
Processing: 2671 - 2700  / Total: 6423
Processing: 2701 - 2730  / Total: 6423
Processing: 2731 - 2760  / Total: 6423
Processing: 2761 - 2790  / Total: 6423
Processing: 2791 - 2820  / Total: 6423
Processing: 2821 - 2850  / Total: 6423
Processing: 2851 - 2880  / Total: 6423
Processing: 2881 - 2910  / Total: 6423
Processing: 2911 - 2940  / Total: 6423
Processing: 2941 - 2970  / Total: 6423
Processing: 2971 - 3000  / Total: 6423
Processing: 3001 - 3030  / Total: 6423
Processing: 3031 - 3060  / Total: 6423
Processing: 3061 - 3090  / Total: 6423
Processing: 3091 - 3120  / Total: 6423
Processing: 3121 - 3150  / Total: 6423
Processing: 3151 - 3180  / Total: 6423
Processing: 3181 - 3210  / Total: 6423
Processing: 3211 - 3240  / Total: 6423
Processing: 3241 - 3270  / Total: 6423
Processing: 3271 - 3300  / Total: 6423
Processing: 3301 - 3330  / Total: 6423
Processing: 3331 - 3360  / Total: 6423
Processing: 3361 - 3390  / Total: 6423
Processing: 3391 - 3420  / Total: 6423
Processing: 3421 - 3450  / Total: 6423
Processing: 3451 - 3480  / Total: 6423
Processing: 3481 - 3510  / Total: 6423
Processing: 3511 - 3540  / Total: 6423
Processing: 3541 - 3570  / Total: 6423
Processing: 3571 - 3600  / Total: 6423
Processing: 3601 - 3630  / Total: 6423
Processing: 3631 - 3660  / Total: 6423
Processing: 3661 - 3690  / Total: 6423
Processing: 3691 - 3720  / Total: 6423
Processing: 3721 - 3750  / Total: 6423
Processing: 3751 - 3780  / Total: 6423
Processing: 3781 - 3810  / Total: 6423
Processing: 3811 - 3840  / Total: 6423
Processing: 3841 - 3870  / Total: 6423
Processing: 3871 - 3900  / Total: 6423
Processing: 3901 - 3930  / Total: 6423
Processing: 3931 - 3960  / Total: 6423
Processing: 3961 - 3990  / Total: 6423
Processing: 3991 - 4020  / Total: 6423
Processing: 4021 - 4050  / Total: 6423
Processing: 4051 - 4080  / Total: 6423
Processing: 4081 - 4110  / Total: 6423
Processing: 4111 - 4140  / Total: 6423
Processing: 4141 - 4170  / Total: 6423
Processing: 4171 - 4200  / Total: 6423
Processing: 4201 - 4230  / Total: 6423
Processing: 4231 - 4260  / Total: 6423
Processing: 4261 - 4290  / Total: 6423
Processing: 4291 - 4320  / Total: 6423
Processing: 4321 - 4350  / Total: 6423
Processing: 4351 - 4380  / Total: 6423
Processing: 4381 - 4410  / Total: 6423
Processing: 4411 - 4440  / Total: 6423
Processing: 4441 - 4470  / Total: 6423
Processing: 4471 - 4500  / Total: 6423
Processing: 4501 - 4530  / Total: 6423
Processing: 4531 - 4560  / Total: 6423
Processing: 4561 - 4590  / Total: 6423
Processing: 4591 - 4620  / Total: 6423
Processing: 4621 - 4650  / Total: 6423
Processing: 4651 - 4680  / Total: 6423
Processing: 4681 - 4710  / Total: 6423
Processing: 4711 - 4740  / Total: 6423
Processing: 4741 - 4770  / Total: 6423
Processing: 4771 - 4800  / Total: 6423
Processing: 4801 - 4830  / Total: 6423
Processing: 4831 - 4860  / Total: 6423
Processing: 4861 - 4890  / Total: 6423
Processing: 4891 - 4920  / Total: 6423
Processing: 4921 - 4950  / Total: 6423
Processing: 4951 - 4980  / Total: 6423
Processing: 4981 - 5010  / Total: 6423
Processing: 5011 - 5040  / Total: 6423
Processing: 5041 - 5070  / Total: 6423
Processing: 5071 - 5100  / Total: 6423
Processing: 5101 - 5130  / Total: 6423
Processing: 5131 - 5160  / Total: 6423
Processing: 5161 - 5190  / Total: 6423
Processing: 5191 - 5220  / Total: 6423
Processing: 5221 - 5250  / Total: 6423
Processing: 5251 - 5280  / Total: 6423
Processing: 5281 - 5310  / Total: 6423
Processing: 5311 - 5340  / Total: 6423
Processing: 5341 - 5370  / Total: 6423
Processing: 5371 - 5400  / Total: 6423
Processing: 5401 - 5430  / Total: 6423
Processing: 5431 - 5460  / Total: 6423
Processing: 5461 - 5490  / Total: 6423
Processing: 5491 - 5520  / Total: 6423
Processing: 5521 - 5550  / Total: 6423
Processing: 5551 - 5580  / Total: 6423
Processing: 5581 - 5610  / Total: 6423
Processing: 5611 - 5640  / Total: 6423
Processing: 5641 - 5670  / Total: 6423
Processing: 5671 - 5700  / Total: 6423
Processing: 5701 - 5730  / Total: 6423
Processing: 5731 - 5760  / Total: 6423
Processing: 5761 - 5790  / Total: 6423
Processing: 5791 - 5820  / Total: 6423
Processing: 5821 - 5850  / Total: 6423
Processing: 5851 - 5880  / Total: 6423
Processing: 5881 - 5910  / Total: 6423
Processing: 5911 - 5940  / Total: 6423
Processing: 5941 - 5970  / Total: 6423
Processing: 5971 - 6000  / Total: 6423
Processing: 6001 - 6030  / Total: 6423
Processing: 6031 - 6060  / Total: 6423
Processing: 6061 - 6090  / Total: 6423
Processing: 6091 - 6120  / Total: 6423
Processing: 6121 - 6150  / Total: 6423
Processing: 6151 - 6180  / Total: 6423
Processing: 6181 - 6210  / Total: 6423
Processing: 6211 - 6240  / Total: 6423
 6241 - 6270  / Total: 6423
Processing: 6271 - 6300  / Total: 6423
Processing: 6301 - 6330  / Total: 6423
Processing: 6331 - 6360  / Total: 6423
Processing: 6361 - 6390  / Total: 6423
Processing: 6391 - 6420  / Total: 6423
Processing: 6421 - 6423  / Total: 6423
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\vsr\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\vsr\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\vsr\resources\gui.py", line 277, in task
    self.sr.run()
  File "D:\vsr\resources\backend\main.py", line 719, in run
    self.sttn_mode(tbar)
  File "D:\vsr\resources\backend\main.py", line 596, in sttn_mode
    self.sttn_mode_with_no_detection(tbar)
  File "D:\vsr\resources\backend\main.py", line 588, in sttn_mode_with_no_detection
    sttn_video_inpaint(input_mask=mask, input_sub_remover=self, tbar=tbar)
  File "D:\vsr\resources\backend\inpaint\sttn_inpaint.py", line 273, in __call__
    image_crop = image[inpaint_area[k][0]:inpaint_area[k][1], :, :]
TypeError: 'NoneType' object is not subscriptable

**Comment by zouzhch** [comment]
我也是一样的问题

**Comment by YaoFANGUK** [comment]
config.py  开启字幕检测

**Comment by fliker09** [comment]
Enabling subtitle detection indeed helped. Still, why it fails without it?

**Comment by sycki** [comment]
> Enabling subtitle detection indeed helped. Still, why it fails without it?

Where can I turn it on? I can't find any relevant configuration items in directory configs.
