### ISSUE TITLE
GUI.py error log

### ISSUE THREAD

**Issue by MichaelSebero** [YaoFANGUK/video-subtitle-remover#36]
/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/setuptools/sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:242: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  interpolation: int = Image.BILINEAR,
/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:288: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  interpolation: int = Image.NEAREST,
/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:304: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  interpolation: int = Image.NEAREST,
/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:321: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  interpolation: int = Image.BICUBIC,
Running Verify Fluid Program ... 
W0126 19:30:46.957288  2808 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.3, Runtime API Version: 11.7
W0126 19:30:46.957516  2808 dynamic_loader.cc:307] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
[<class 'RuntimeError'>] In user code:

    File "gui.py", line 394, in <module>
      subtitleRemoverGUI = SubtitleRemoverGUI()
    File "gui.py", line 26, in __init__
      fluid.install_check.run_check()
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 142, in run_check
      test_simple_exe()
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 130, in test_simple_exe
      simple_layer0 = SimpleLayer(input_size=2)
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 37, in __init__
      self._linear1 = nn.Linear(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/dygraph/nn.py", line 993, in __init__
      self.weight = self.create_parameter(shape=[input_dim, output_dim],
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 471, in create_parameter
      return self._helper.create_parameter(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3988, in create_parameter
      initializer(param, self)
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 56, in __call__
      return self.forward(param, block)
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 184, in forward
      op = block.append_op(type="fill_constant",
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4040, in append_op
      op = Operator(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:60)
      [operator < fill_constant > error]
Traceback (most recent call last):
  File "gui.py", line 394, in <module>
    subtitleRemoverGUI = SubtitleRemoverGUI()
  File "gui.py", line 26, in __init__
    fluid.install_check.run_check()
  File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 142, in run_check
    test_simple_exe()
  File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 138, in test_simple_exe
    exe0.run(startup_prog)
  File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
RuntimeError: In user code:

    File "gui.py", line 394, in <module>
      subtitleRemoverGUI = SubtitleRemoverGUI()
    File "gui.py", line 26, in __init__
      fluid.install_check.run_check()
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 142, in run_check
      test_simple_exe()
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 130, in test_simple_exe
      simple_layer0 = SimpleLayer(input_size=2)
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/install_check.py", line 37, in __init__
      self._linear1 = nn.Linear(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/dygraph/nn.py", line 993, in __init__
      self.weight = self.create_parameter(shape=[input_dim, output_dim],
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 471, in create_parameter
      return self._helper.create_parameter(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3988, in create_parameter
      initializer(param, self)
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 56, in __call__
      return self.forward(param, block)
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 184, in forward
      op = block.append_op(type="fill_constant",
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4040, in append_op
      op = Operator(
    File "/home/user/miniconda3/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:60)
      [operator < fill_constant > error]

**Comment by YaoFANGUK** [comment]
cudnn 环境没装好
