### ISSUE TITLE
出现报错如何解决？-

### ISSUE THREAD

**Issue by vt2744** [YaoFANGUK/video-subtitle-remover#72]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\username\Downloads\xxx\vsr\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\username\Downloads\xxx\vsr\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\vt274\Downloads\xxx\vsr\resources\gui.py", line 277, in task
    self.sr.run()
  File "C:\Users\username\Downloads\xxx\vsr\resources\backend\main.py", line 719, in run
    self.sttn_mode(tbar)
  File "C:\Users\username\Downloads\xxx\vsr\resources\backend\main.py", line 596, in sttn_mode
    self.sttn_mode_with_no_detection(tbar)
  File "C:\Users\username\Downloads\xxx\vsr\resources\backend\main.py", line 588, in sttn_mode_with_no_detection
    sttn_video_inpaint(input_mask=mask, input_sub_remover=self, tbar=tbar)
  File "C:\Users\username\Downloads\xxx\vsr\resources\backend\inpaint\sttn_inpaint.py", line 273, in __call__
    image_crop = image[inpaint_area[k][0]:inpaint_area[k][1], :, :]
TypeError: 'NoneType' object is not subscriptable

**Comment by aloxc** [comment]
我试验出问题所在，可能你的视频编码格式是这样的yuv420p(tv, gbr/reserved/reserved, progressive),我试验过程中如果是这样的格式就会有问题，解决办法就是把视频拖到剪映什么里面，然后导出再去字幕，我也是无意中发现的，我有个视频是使用录屏软件录的，就不行，后来我就放到剪映中导出再操作就没问题了。  
 @YaoFANGUK  我把出错视频提供 
![Snipaste_2024-08-02_21-10-15](https://github.com/user-attachments/assets/93914712-b1ec-45a3-9700-21c5ce093673)
[Uploading b.zip…]()

**Comment by aloxc** [comment]
期待有人能修复这个问题

**Comment by fliker09** [comment]
Enable subtitle detection and it will work. A piece of advice - use CLI instead of GUI, it will work MUCH faster. Though it will ignore the subarea, which sucks. Had to modify main.py and give it my desired subarea.
